### ISSUE TITLE
Resolve issue on Drupal.org

### ISSUE THREAD

**Issue by frob** [sonnym/travis-ci-drupal-module-example#4]
Create a 8.x branch on conform to the Drupal Module branch version system.

https://drupal.org/node/2248913

This is a great idea. By the way this module is a great idea.

**Comment by sonnym** [comment]
I have been meaning to take care of that.  It'll probably happen this weekend.  Thanks for the props!

**Comment by sonnym** [comment]
I finally got around to updating the branches, but the tests do not yet work for Drupal 8.  As I am not actively developing modules for Drupal at this time, I am, unfortunately, not going to spend the time figuring out what is wrong, but I will merge any pull requests that fix this issue!
